// <auto-generated />
namespace AlimentosSantiago.Dao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModificacionBaseDatos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModificacionBaseDatos));
        
        string IMigrationMetadata.Id
        {
            get { return "201604281904027_ModificacionBaseDatos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
